wifi: Fix use of undeclared identifier 'WIFI_FEATURE_DYNAMIC_SET_MAC'.
Introduced with commit eb42eec

hardware/interfaces/wifi/1.5/default/wifi_iface_util.cpp:67:32: error: use of undeclared identifier 'WIFI_FEATURE_DYNAMIC_SET_MAC'
    if (!(legacy_feature_set & WIFI_FEATURE_DYNAMIC_SET_MAC) &&
                               ^
hardware/interfaces/wifi/1.5/default/wifi_iface_util.cpp:75:32: error: use of undeclared identifier 'WIFI_FEATURE_DYNAMIC_SET_MAC'
    if (!(legacy_feature_set & WIFI_FEATURE_DYNAMIC_SET_MAC) &&

Signed-off-by: spezi77 <spezi7713@gmx.net>
Change-Id: I94dfc931a79f34fdd82f19c18d8884445945e59e