Revert "Add call to get camera device version"
This reverts commit 669be8f0d018f0eb16ee13e6406c98e8aa4ce9c7.

Required for instantnoodle @fKm86

hardware/interfaces/camera/common/1.0/default/CameraModule.cpp:274:22: error: no member named 'get_camera_device_version' in 'camera_module'
            mModule->get_camera_device_version != NULL) {
            ~~~~~~~  ^
hardware/interfaces/camera/common/1.0/default/CameraModule.cpp:275:24: error: no member named 'get_camera_device_version' in 'camera_module'
        ret = mModule->get_camera_device_version(cameraId, version);
              ~~~~~~~  ^
2 errors generated.